apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app-platform.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app-platform.labels" . | nindent 4 }}
data:
  # Add your config data here
  # config.yaml: |
  #   key: value